stages:
  - build
  - publish

build:
    stage: build
    rules:
      - if: $CI_BUILD_REF_NAME == "master"
      - if: $CI_BUILD_REF_NAME == "develop"
    script:
        - docker build -t "$CI_REGISTRY_IMAGE/base:$CI_BUILD_REF_SLUG" .
        - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
        - docker push $CI_REGISTRY_IMAGE/base:$CI_BUILD_REF_SLUG
        - docker rmi $CI_REGISTRY_IMAGE/base:$CI_BUILD_REF_SLUG
        - docker image prune -f
    tags:
        - ser-staging-04
publish:
    when: manual
    needs:
      - job: build
    stage: publish
    rules:
      - if: $CI_BUILD_REF_NAME == "master"
        variables:
          PROJECT_PATH: "aiqueue-master"
      - if: $CI_BUILD_REF_NAME == "develop"
        variables:
          PROJECT_PATH: "aiqueue-develop"
    script:
        - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
        - docker pull $CI_REGISTRY_IMAGE/base:$CI_BUILD_REF_SLUG
        - docker compose -f /opt/$PROJECT_PATH/conf/docker-compose.yml up -d landing
    tags:
        - ser-aiqueue-01
